export const students = [

    {
        "id": 1,
        "first_name": "Bebe",
        "last_name": "Millthorpe",
        "grade_id": 1,
        "background_story": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "status": "orci vehicula",
        "age": 77,
        "insurance_card": false,
        "insurance_expiration": "10/1/2019",
        "birth_dertificate": true,
        "special_needs": "pede malesuada in imperdiet et commodo vulputate justo in blandit",
        "representative": "Bebe Millthorpe",
        "contact_info": "bmillthorpe0@theatlantic.com",
        "visits": 19
      }, {
        "id": 2,
        "first_name": "Shell",
        "last_name": "Lown",
        "grade_id": 2,
        "background_story": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
        "status": "at nibh",
        "age": 20,
        "insurance_card": true,
        "insurance_expiration": "10/13/2019",
        "birth_dertificate": false,
        "special_needs": "in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum",
        "representative": "Shell Lown",
        "contact_info": "slown1@yale.edu",
        "visits": 36
      }, {
        "id": 3,
        "first_name": "Kat",
        "last_name": "Babb",
        "grade_id": 3,
        "background_story": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
        "status": "sed justo pellentesque",
        "age": 25,
        "insurance_card": false,
        "insurance_expiration": "2/11/2019",
        "birth_dertificate": false,
        "special_needs": "nulla tempus vivamus in felis eu sapien cursus vestibulum proin",
        "representative": "Kat Babb",
        "contact_info": "kbabb2@upenn.edu",
        "visits": 26
      }, {
        "id": 4,
        "first_name": "Samantha",
        "last_name": "Findon",
        "grade_id": 4,
        "background_story": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
        "status": "elit ac nulla",
        "age": 48,
        "insurance_card": true,
        "insurance_expiration": "10/7/2019",
        "birth_dertificate": false,
        "special_needs": "vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id",
        "representative": "Samantha Findon",
        "contact_info": "sfindon3@soundcloud.com",
        "visits": 71
      }, {
        "id": 5,
        "first_name": "Moll",
        "last_name": "Karpets",
        "grade_id": 5,
        "background_story": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
        "status": "volutpat dui",
        "age": 37,
        "insurance_card": false,
        "insurance_expiration": "5/3/2019",
        "birth_dertificate": false,
        "special_needs": "volutpat erat quisque erat eros viverra eget congue eget semper",
        "representative": "Moll Karpets",
        "contact_info": "mkarpets4@boston.com",
        "visits": 52
      }, {
        "id": 6,
        "first_name": "Charmian",
        "last_name": "McKinless",
        "grade_id": 6,
        "background_story": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        "status": "dictumst etiam",
        "age": 62,
        "insurance_card": false,
        "insurance_expiration": "11/18/2019",
        "birth_dertificate": true,
        "special_needs": "ac enim in tempor turpis nec euismod scelerisque quam turpis",
        "representative": "Charmian McKinless",
        "contact_info": "cmckinless5@cbslocal.com",
        "visits": 31
      }, {
        "id": 7,
        "first_name": "Isabella",
        "last_name": "Klyn",
        "grade_id": 7,
        "background_story": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "status": "accumsan tortor",
        "age": 54,
        "insurance_card": true,
        "insurance_expiration": "2/10/2019",
        "birth_dertificate": false,
        "special_needs": "quis libero nullam sit amet turpis elementum ligula vehicula consequat",
        "representative": "Isabella Klyn",
        "contact_info": "iklyn6@npr.org",
        "visits": 50
      }, {
        "id": 8,
        "first_name": "Bendix",
        "last_name": "Prewer",
        "grade_id": 8,
        "background_story": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        "status": "erat vestibulum sed",
        "age": 92,
        "insurance_card": true,
        "insurance_expiration": "3/16/2019",
        "birth_dertificate": true,
        "special_needs": "non quam nec dui luctus rutrum nulla tellus in sagittis",
        "representative": "Bendix Prewer",
        "contact_info": "bprewer7@livejournal.com",
        "visits": 8
      }, {
        "id": 9,
        "first_name": "Gil",
        "last_name": "Damiata",
        "grade_id": 9,
        "background_story": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
        "status": "nulla neque libero",
        "age": 74,
        "insurance_card": true,
        "insurance_expiration": "7/24/2019",
        "birth_dertificate": true,
        "special_needs": "pede posuere nonummy integer non velit donec diam neque vestibulum",
        "representative": "Gil Damiata",
        "contact_info": "gdamiata8@lulu.com",
        "visits": 18
      }, {
        "id": 10,
        "first_name": "Dicky",
        "last_name": "Horlick",
        "grade_id": 10,
        "background_story": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        "status": "duis bibendum",
        "age": 73,
        "insurance_card": true,
        "insurance_expiration": "11/18/2019",
        "birth_dertificate": false,
        "special_needs": "lobortis vel dapibus at diam nam tristique tortor eu pede",
        "representative": "Dicky Horlick",
        "contact_info": "dhorlick9@123-reg.co.uk",
        "visits": 73
      }, {
        "id": 11,
        "first_name": "Edward",
        "last_name": "Van der Hoven",
        "grade_id": 11,
        "background_story": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        "status": "at lorem integer",
        "age": 18,
        "insurance_card": false,
        "insurance_expiration": "11/5/2019",
        "birth_dertificate": true,
        "special_needs": "aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien",
        "representative": "Edward Van der Hoven",
        "contact_info": "evana@apache.org",
        "visits": 21
      }, {
        "id": 12,
        "first_name": "Nicki",
        "last_name": "Holborn",
        "grade_id": 12,
        "background_story": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
        "status": "porta volutpat erat",
        "age": 56,
        "insurance_card": false,
        "insurance_expiration": "9/20/2019",
        "birth_dertificate": true,
        "special_needs": "aliquet at feugiat non pretium quis lectus suspendisse potenti in",
        "representative": "Nicki Holborn",
        "contact_info": "nholbornb@wikia.com",
        "visits": 59
      }, {
        "id": 13,
        "first_name": "Olivette",
        "last_name": "Payn",
        "grade_id": 13,
        "background_story": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        "status": "justo aliquam quis",
        "age": 88,
        "insurance_card": true,
        "insurance_expiration": "11/10/2019",
        "birth_dertificate": true,
        "special_needs": "tristique fusce congue diam id ornare imperdiet sapien urna pretium",
        "representative": "Olivette Payn",
        "contact_info": "opaync@dmoz.org",
        "visits": 36
      }, {
        "id": 14,
        "first_name": "Patton",
        "last_name": "Colum",
        "grade_id": 14,
        "background_story": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
        "status": "dui maecenas",
        "age": 9,
        "insurance_card": false,
        "insurance_expiration": "3/6/2019",
        "birth_dertificate": true,
        "special_needs": "morbi non lectus aliquam sit amet diam in magna bibendum",
        "representative": "Patton Colum",
        "contact_info": "pcolumd@youtube.com",
        "visits": 2
      }, {
        "id": 15,
        "first_name": "Toddy",
        "last_name": "Liepins",
        "grade_id": 15,
        "background_story": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
        "status": "ornare imperdiet",
        "age": 21,
        "insurance_card": true,
        "insurance_expiration": "8/15/2019",
        "birth_dertificate": true,
        "special_needs": "turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
        "representative": "Toddy Liepins",
        "contact_info": "tliepinse@ehow.com",
        "visits": 61
      }





]

    




